- name: Run Custom Script
  hosts: all
  become: yes
  tasks:
    - name: Execute the script
      ansible.builtin.shell: /home/appsupport/aws_restart/test3.sh
      register: script_output

    - name: Show script output
      debug:
        var: script_output
